#!/bin/bash

set -e

echo "=== How to Verify Tunnel is Working End-to-End ==="
echo ""
echo "1. Check Agent & Tunnel CRs:"
echo "   kubectl -n xpos-system get agents,tunnels"
echo ""
echo "2. Check HTTPRoute is Accepted:"
echo "   kubectl -n xpos-system get httproute -o yaml | grep -A5 'conditions:'"
echo ""
echo "3. Check per-pod Service exists:"
echo "   kubectl -n xpos-system get svc | grep xpos-relay-"
echo ""
echo "4. Check GatewayClass is Accepted:"
echo "   kubectl get gatewayclass"
echo ""
echo "5. Check Gateway status:"
echo "   kubectl -n xpos-system get gateway xpos-gateway -o yaml | grep -A10 'status:'"
echo ""
echo "6. Check Envoy Gateway picked up route:"
echo "   kubectl -n envoy-gateway-system get pods"
echo "   kubectl -n envoy-gateway-system logs deployment/envoy-xpos-system-xpos-gateway-f61e3240 --tail=20"
echo ""
echo "7. Test the tunnel (requires port-forwards):"
echo "   # Port-forward to Envoy Gateway"
echo "   kubectl -n envoy-gateway-system port-forward service/eg 18080:80 &"
echo "   # Test request"
echo "   curl -H 'Host: dev.xpos-io.com' http://localhost:18080/"
echo ""