name: 🐞 Bug Report
description: Report an issue with the project
title: "[BUG] <brief description>"
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: "### 🐛 Please describe the bug"

  - type: textarea
    id: description
    attributes:
      label: "Describe the issue"
      description: "Provide a clear and concise description of the problem."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs & Screenshots"
      description: "If applicable, add logs/screenshots to help explain your problem."
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Provide details (OS, browser, software version, etc.)."
    validations:
      required: true
